module.exports = {
  capitalize: require("./capitalize"),
  toTitleCase: require("./toTitleCase"),
  toUpperCase: require("./toUpperCase"),
  toCamelCase: require("./toCamelCase"),
  toLowerCase: require("./toLowerCase"),
  toPascalCase: require("./toPascalCase"),
  toSnakeCase: require("./toSnakeCase"),
  toSlugCase: require("./toSlugCase"),
  sum: require("./sum"),
  min: require("./min"),
  max: require("./max"),
  random: require("./random"),
  chunk: require("./chunk"),
  isEquivalent: require("./isEquivalent"),
  unique: require("./unique"),
  head: require("./head"),
  last: require("./last"),
  fromPairs: require("./fromPairs"),
  hashCode: require("./hashCode"),
  insert: require("./insert"),
  deleteAt: require("./deleteAt"),
  at: require("./at"),
};
